In [55]:
import pandas as pd

In [56]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [57]:
orders = pd.read_excel("Task_03_Cleaned_Dataset.xlsx", sheet_name="Orders_Cleaned")
orders.head()

,OrderID,CustomerID,CustomerName,Email,Phone,City,Category,Product,Quantity,UnitPrice,...,PaymentMethod,OrderDate,Status,Rating,TotalAmount,FinalAmount,PriceFlag,QuantityFlag,RatingFlag,DateFlag
0,ORD013233,CUST04801,Vikas Sharma,vikas.sharma610@gmail.com,9738787236,Jaipur,Home Decor,Table Runner,2,1589.66,...,Cash on Delivery,2022-12-06,Cancelled,1,3020.35,3020.35,Valid,Valid,Valid,Valid
1,ORD018894,CUST00464,Aarav Iyer,aarav.iyer690@yahoo.com,9435901706,Delhi,Home Decor,Photo Frame,3,1105.70,...,UPI,2022-10-12,Pending,3,3151.25,3151.25,Valid,Valid,Valid,Valid
2,ORD002166,CUST03121,Kiran Kapoor,kiran.kapoor954@gmail.com,9777489925,Delhi,Furniture,Tv Stand,6,5918.02,...,Net Banking,2023-03-21,Processing,4,30181.90,30181.90,Valid,Valid,Valid,Valid
3,ORD004089,CUST02855,Deepa Singh,deepa.singh398@gmail.com,9283637528,Kanpur,Sports,Football,1,1047.76,...,Debit Card,2023-03-08,Delivered,4,1047.76,1047.76,Valid,Valid,Valid,Valid
4,ORD012533,CUST01038,Diana Iyer,diana.iyer219@yahoo.com,9807232466,Mumbai,Home Decor,Cushion Cover,1,2102.00,...,Debit Card,2022-03-31,Delivered,2,1576.50,1576.50,Valid,Valid,Valid,Valid

In [58]:
customers=pd.read_excel("Task_03_Cleaned_Dataset.xlsx", sheet_name="Customers_Ref")
customers.head()

,CustomerID,CustomerName,Email,Phone,City
0,CUST02067,Vikas Singh,vikas.singh277@gmail.com,9365423086,Kanpur
1,CUST02923,Charlie Malhotra,charlie.malhotra124@yahoo.com,9978346184,Kanpur
2,CUST01100,Zara Mehta,zara.mehta744@gmail.com,9749147872,Nagpur
3,CUST01859,Kiran Rao,kiran.rao540@gmail.com,9767285726,Lucknow
4,CUST00240,Vijay Das,vijay.das225@gmail.com,Unknown,Pune

In [59]:
# Dataset information
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20088 entries, 0 to 20087
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        20088 non-null  object
 1   CustomerID     20088 non-null  object
 2   CustomerName   20088 non-null  object
 3   Email          20088 non-null  object
 4   Phone          20041 non-null  object
 5   City           20088 non-null  object
 6   Category       20088 non-null  object
 7   Product        20088 non-null  object
 8   Quantity       20088 non-null  int64
 9   UnitPrice      20088 non-null  float64
 10  Discount_Pct   20088 non-null  int64
 11  PaymentMethod  20088 non-null  object
 12  OrderDate      20088 non-null  datetime64[ns]
 13  Status         20088 non-null  object
 14  Rating         20088 non-null  int64
 15  TotalAmount    20088 non-null  float64
 16  FinalAmount    20088 non-null  float64
 17  PriceFlag      20088 non-null  object
 18  QuantityFlag   20088 non-null  object
 19  RatingFlag     20088 non-null  object
 20  DateFlag       20088 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(14)
memory usage: 3.2+ MB

In [60]:
# Statistical summary
orders.describe()

,Quantity,UnitPrice,Discount_Pct,OrderDate,Rating,TotalAmount,FinalAmount
count,20088.00,20088.00,20088.00,20088,20088.00,20088.00,20088.00
mean,5.50,1219.59,12.58,2023-07-17 17:19:12.688171776,3.50,5921.46,5845.62
min,-5.00,-500.00,0.00,2022-01-01 00:00:00,-1.00,43.05,-48770.60
25%,3.00,450.34,5.00,2022-10-07 00:00:00,3.00,1547.35,1496.58
50%,6.00,872.80,10.00,2023-07-17 00:00:00,4.00,3507.29,3451.61
75%,8.00,1415.70,20.00,2024-04-16 00:00:00,5.00,7264.41,7230.27
max,10.00,7492.61,200.00,2027-05-02 00:00:00,10.00,71626.60,71626.60
std,2.92,1304.43,11.83,NaN,1.48,7723.60,7783.99

In [61]:
# Check missing values
orders.isnull().sum()

OrderID           0
CustomerID        0
CustomerName      0
Email             0
Phone            47
City              0
Category          0
Product           0
Quantity          0
UnitPrice         0
Discount_Pct      0
PaymentMethod     0
OrderDate         0
Status            0
Rating            0
TotalAmount       0
FinalAmount       0
PriceFlag         0
QuantityFlag      0
RatingFlag        0
DateFlag          0
dtype: int64

In [62]:
# Dataset shape
print("Shape:", orders.shape)

Shape: (20088, 21)

In [63]:
# Column names
print(orders.columns)

Index(['OrderID', 'CustomerID', 'CustomerName', 'Email', 'Phone', 'City',
       'Category', 'Product', 'Quantity', 'UnitPrice', 'Discount_Pct',
       'PaymentMethod', 'OrderDate', 'Status', 'Rating', 'TotalAmount',
       'FinalAmount', 'PriceFlag', 'QuantityFlag', 'RatingFlag', 'DateFlag'],
      dtype='object')

In [64]:
print(customers.columns)

Index(['CustomerID', 'CustomerName', 'Email', 'Phone', 'City'], dtype='object')

# Handle Missing Values and Duplicates

In [65]:
# Check missing values
print(orders.isnull().sum())

OrderID           0
CustomerID        0
CustomerName      0
Email             0
Phone            47
City              0
Category          0
Product           0
Quantity          0
UnitPrice         0
Discount_Pct      0
PaymentMethod     0
OrderDate         0
Status            0
Rating            0
TotalAmount       0
FinalAmount       0
PriceFlag         0
QuantityFlag      0
RatingFlag        0
DateFlag          0
dtype: int64

In [66]:
# Check duplicate rows
print("Duplicate Rows:", orders.duplicated().sum())

Duplicate Rows: 40

In [67]:
# Remove duplicates (if any)
orders = orders.drop_duplicates()

# Clean and Transform Columns

In [68]:
# Convert Category to Proper Case
orders["Category"] = orders["Category"].str.title()

In [69]:
# Trim CustomerName
orders["CustomerName"] = orders["CustomerName"].str.strip()

In [70]:
# Convert OrderDate to datetime
orders["OrderDate"] = pd.to_datetime(orders["OrderDate"])

# Fix City Names and Ratings

In [71]:
# Fix city names
orders["City"] = orders["City"].replace({
    "Hydrabad": "Hyderabad",
    "Banglaore": "Bangalore",
    "Delhl": "Delhi"
})

In [72]:
orders["City"] = orders["City"].replace({
    "Chennnai": "Chennai"
})

In [73]:
# Check unique city names
print("Unique Cities:")
print(sorted(orders["City"].unique()))

Unique Cities:
['Ahmedabad', 'Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Indore', 'Jaipur', 'Kanpur', 'Kolkata', 'Lucknow', 'Mumbai', 'Nagpur', 'Pune', 'Surat', 'Unknown']

In [74]:
# Check rating values
print("\nUnique Ratings:")
print(sorted(orders["Rating"].unique()))

Unique Ratings:
[np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(10)]

# Perform Grouping and Analysis

In [75]:
#1. Revenue by Category
category_revenue = orders.groupby("Category")["FinalAmount"].sum().sort_values(ascending=False)
print("Revenue by Category:")
print(category_revenue)

Revenue by Category:
Category
Furniture     40757600.12
Home Decor    13816524.94
Electronics   12308169.18
Sports        10735568.09
Toys           9306776.45
Automotive     7827891.80
Clothing       7527040.52
Beauty         7094198.65
Books          5214545.67
Groceries      2612484.79
Name: FinalAmount, dtype: float64

In [76]:
#2. Top 5 Cities by Revenue
top_cities = orders.groupby("City")["FinalAmount"].sum().sort_values(ascending=False).head(5)
print("\nTop 5 Cities:")
print(top_cities)

Top 5 Cities:
City
Surat       8670226.19
Kanpur      8549965.64
Mumbai      8452220.37
Hyderabad   8283917.36
Bangalore   8144539.50
Name: FinalAmount, dtype: float64

In [77]:
# Top 5 Customers
top_customers = orders.groupby("CustomerName")["FinalAmount"].sum().sort_values(ascending=False).head(5)

print("Top 5 Customers:")
print(top_customers)

Top 5 Customers:
CustomerName
Unknown         5000242.71
Sanjay Sharma    329549.11
Gaurav Kumar     320590.22
Ivy Reddy        299061.61
Sanjay Rao       297510.72
Name: FinalAmount, dtype: float64

# Generate Summary Outputs

In [80]:
print("========== SUMMARY ==========")

print("Total Orders:", len(orders))
print("Unique Customers:", orders["CustomerID"].nunique())
print("Total Revenue:", round(orders["FinalAmount"].sum(), 2))
print("Average Rating:", round(orders["Rating"].mean(), 2))

print("\nRevenue by Category:")
print(category_revenue)

print("\nTop 5 Cities:")
print(top_cities)

print("\nTop 5 Customers:")
print(top_customers)

========== SUMMARY ==========
Total Orders: 20048
Unique Customers: 4917
Total Revenue: 117200800.2
Average Rating: 3.5

Revenue by Category:
Category
Furniture     40757600.12
Home Decor    13816524.94
Electronics   12308169.18
Sports        10735568.09
Toys           9306776.45
Automotive     7827891.80
Clothing       7527040.52
Beauty         7094198.65
Books          5214545.67
Groceries      2612484.79
Name: FinalAmount, dtype: float64

Top 5 Cities:
City
Surat       8670226.19
Kanpur      8549965.64
Mumbai      8452220.37
Hyderabad   8283917.36
Bangalore   8144539.50
Name: FinalAmount, dtype: float64

Top 5 Customers:
CustomerName
Unknown         5000242.71
Sanjay Sharma    329549.11
Gaurav Kumar     320590.22
Ivy Reddy        299061.61
Sanjay Rao       297510.72
Name: FinalAmount, dtype: float64